server:
  port: 8100

spring:
  application:
    name: product-catalog-service
  datasource:
    url: jdbc:h2:file:./data/productsdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true
  eureka:
    client:
      service-url:
        defaultZone: http://localhost:8761/eureka/
  h2:
    console:
      enabled: true
      path: /h2-console
